# Welcome to Jekyll!

# Website settings
title: Jack Ellenberger
description: CS Engineer, Braintree Dev, UofC Grad
keywords: Jack,Ellenberger,JackEllenberger,ellenberger.zone,jack.ellenberger.zone,braintree,uchicago
# baseurl: /
url: jack.ellenberger.zone
img_path: /static/assets/img/blog

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Jack Ellenberger  # Be used at blog posts' author.
  first_name: Jack  # Be used at index page about me section.
  last_name: Ellenberger  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: jackellenberger  # Leave blank if you don't have now
  linkedin_id: jack-ellenberger-149134b4 # Leave blank if you don't have now
  facebook_username: # Leave blank if you don't have now
  twitter_username: # Leave blank if you don't have now
  email: jellenberger@uchicago.edu  # Leave blank if you don't have now
  cv: /static/assets/ellenberger_resume.pdf  # A online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: fa-credit-card
    - name: fa-i-cursor
  skill_icon2:
    - name: fa-github
    - name: fa-linux
  desc: Introduce myself will be here.  # Describe yourself.


# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: on  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on
blog_carousel: on

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
